version: '3'

services:
    mongo:
      image: mongo:latest
      environment:
          MONGO_INITDB_ROOT_USERNAME : "${MONGO_USER}"
          MONGO_INITDB_ROOT_PASSWORD : "${MONGO_PWD}"
          MONGO_INITDB_DATABASE : "${MONGO_DATABASE}"
      ports:
        - "${MONGO_PORT}:${MONGO_PORT}"
      volumes:
        - ./data:/data/db
      network_mode: "host"

    color-match:
      build: .
      ports:
        - "${FLASK_PORT}:${FLASK_PORT}"
      network_mode: "host"

volumes:
  data:
    driver: local
